### PR TITLE
chore(contrib): add contributing guidelines & finish User/Author page

### LINKED ISSUE #14: Add instructions to README
We need to have instructions about how to start the app for development on a local machine with and without docker.

### LINKED ISSUE #26: [Django User] When a User is excluded, its Author, Models and Predictions are excluded
The way the Models are related, deleting an User from the database will generate a cascade event where every insert from this user is also deleted. I'm opening this issue to discuss if it will be the standard procedure for the API or the Author should only reference the User, and not have an OneToOne relationship with them.

From my perspective, there's nothing wrong with it. Thinking from an User's perspective, the choice of deleting the user is also the choice of deleting everything related to it. Now, at the database point of view, it would mean to lose data.

### LINKED ISSUE #29: [Django API] Hide Authors that don't have any predictions from the API calls
There is no point to listing Authors if they don't have any Model nor Prediction, the API calls will return only Authors with content in it

### LINKED ISSUE #33: [Django] Replace all JS and CSS externally imported by local scripts
DataTables JS for instance is taking 2ms to load

### PR DESCRIPTION
**Pull request by luabida**
fix #14
fix #29 
fix #33 
fix #26

### CODE REVIEW

**Comment by luabida** [comment]
More or less how the models will appear on the profile:

image

**Comment by luabida** [comment]
I'm currently testing with a large amount of predictions (100k) and the fetching GET request is taking forever, either using python `requests` and in the user page (+- 10 mins to load 😥). Do you have any ideas about this situation @fccoelho ?

OBS: The predictions have a considering comment and a medium size (?) prediction:
```
{
    "id": 99,
    "model": {
      "id": 105,
      "name": "Test python 94",
      "description": "Some nice description here",
      "author": {
        "user": {
          "name": "Luã Bida Vacaro",
          "username": "luabida"
        },
        "institution": null
      },
      "repository": "https://github.com/Mosqlimate-project/Data-platform",
      "implementation_language": "python",
      "type": "python test"
    },
    "description": "\n\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nisi nisi, viverra nec sem a, pulvinar tempus felis. Aenean et dapibus purus. Aenean auctor accumsan leo, luctus fringilla mi scelerisque eget. Donec efficitur nisl a tortor rutrum facilisis. Duis faucibus efficitur sem nec faucibus. Aenean tempor eros eget convallis euismod. Integer eleifend aliquam velit, non tristique nibh lobortis quis. Etiam dolor eros, commodo eleifend sapien sit amet, venenatis porta turpis. Ut vel orci eget turpis sollicitudin semper a eu dui.\n\nMauris posuere nisi a fringilla tempor. Nunc ut lectus in nisl feugiat faucibus id ut sem. Duis euismod molestie pharetra. Integer blandit felis sagittis velit molestie vestibulum. Aenean sagittis augue sed laoreet blandit. Sed gravida nisl velit, at porttitor est molestie et. Phasellus erat erat, vulputate non gravida et, mattis nec erat. Fusce sit amet quam lectus. Ut vestibulum a quam sed pretium. Pellentesque tempor elementum arcu, non fringilla quam semper a.\n\nFusce lacus nisl, porta vel elementum sit amet, condimentum vitae est. Duis eu justo ipsum. Nam faucibus erat vitae dolor mattis interdum. Quisque dictum nunc a convallis fringilla. Nullam a iaculis nisi, id accumsan ligula. Fusce suscipit nec elit id ultricies. Curabitur a vulputate libero, ut placerat diam. In volutpat eleifend eros at aliquet. Praesent consequat dolor ut mattis maximus.\n\nSed ac lacus in quam volutpat maximus sed viverra urna. Duis facilisis metus eget tellus porta, eget vehicula purus feugiat. Nam eget commodo arcu. Nam consectetur orci non eros tempus pellentesque. Nulla turpis massa, ullamcorper ac aliquam quis, auctor vel augue. Aliquam posuere elementum arcu ac consequat. Vestibulum in imperdiet lorem, eu rutrum metus. Duis in libero feugiat, porttitor leo at, tristique tellus. Sed nec suscipit leo. Praesent ultrices vel metus sit amet pulvinar.\n\nNunc quis faucibus metus. Duis ac velit condimentum, varius risus at, fermentum felis. Sed maximus luctus justo, laoreet finibus diam efficitur at. Nulla dignissim a nisl sit amet euismod. Quisque auctor nulla eu ligula posuere lobortis. Vestibulum commodo nibh sed tortor maximus dictum. Sed vel dolor mattis, iaculis mi sollicitudin, varius metus. Donec dignissim purus quis nulla commodo, at tempor nisi aliquam. Aenean eleifend urna non nisi tempus, id pellentesque tortor suscipit.\n",
    "commit": "97ab99cd102efghih",
    "predict_date": "2023-07-21",
    "prediction": {
      "users": [
        {
          "id": 1,
          "age": 28,
          "name": "John Doe",
          "email": "john.doe@example.com"
        },
        {
          "id": 2,
          "age": 32,
          "name": "Jane Smith",
          "email": "jane.smith@example.com"
        },
        {
          "id": 3,
          "age": 24,
          "name": "Alice Johnson",
          "email": "alice.johnson@example.com"
        },
        {
          "id": 4,
          "age": 35,
          "name": "Bob Williams",
          "email": "bob.williams@example.com"
        }
      ],
      "products": [
        {
          "id": 1,
          "name": "Phone",
          "price": 499.99,
          "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius, dui id consequat aliquam, lorem urna semper neque, et luctus tortor urna quis ex. Proin vitae magna a urna hendrerit volutpat in et sapien."
        },
        {
          "id": 2,
          "name": "Laptop",
          "price": 999.99,
          "description": "Praesent lobortis, mauris ut bibendum iaculis, tortor ex cursus turpis, in tincidunt turpis massa ut diam. In hac habitasse platea dictumst. Morbi vestibulum scelerisque ultricies. Sed eu finibus odio. Nulla facilisi."
        },
        {
          "id": 3,
          "name": "Camera",
          "price": 299.99,
          "description": "Vestibulum facilisis odio id felis interdum, id faucibus lorem ultricies. Aenean pretium erat in bibendum convallis. Suspendisse id ultrices metus. Aliquam fringilla nibh vel nisl gravida aliquam. Integer sed sem felis."
        },
        {
          "id": 4,
          "name": "Headphones",
          "price": 129.99,
          "description": "Sed sit amet orci arcu. Fusce sed nisi id urna lobortis venenatis. Cras convallis purus et felis finibus, eu fringilla mi hendrerit. Etiam eu elit non sem blandit auctor ut sed quam."
        },
        {
          "id": 5,
          "name": "Phone",
          "price": 499.99,
          "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius, dui id consequat aliquam, lorem urna semper neque, et luctus tortor urna quis ex. Proin vitae magna a urna hendrerit volutpat in et sapien."
        },
        {
          "id": 6,
          "name": "Laptop",
          "price": 999.99,
          "description": "Praesent lobortis, mauris ut bibendum iaculis, tortor ex cursus turpis, in tincidunt turpis massa ut diam. In hac habitasse platea dictumst. Morbi vestibulum scelerisque ultricies. Sed eu finibus odio. Nulla facilisi."
        },
        {
          "id": 7,
          "name": "Camera",
          "price": 299.99,
          "description": "Vestibulum facilisis odio id felis interdum, id faucibus lorem ultricies. Aenean pretium erat in bibendum convallis. Suspendisse id ultrices metus. Aliquam fringilla nibh vel nisl gravida aliquam. Integer sed sem felis."
        },
        {
          "id": 8,
          "name": "Headphones",
          "price": 129.99,
          "description": "Sed sit amet orci arcu. Fusce sed nisi id urna lobortis venenatis. Cras convallis purus et felis finibus, eu fringilla mi hendrerit. Etiam eu elit non sem blandit auctor ut sed quam."
        }
      ]
    }
  }
```

**Comment by luabida** [comment]
while searching for django pagination, I notice django-ninja also has pagination support, I'm adding it to the list requests

https://django-ninja.rest-framework.com/guides/response/pagination/

**Review by fccoelho — APPROVED** [review]
Looking good

**Comment by luabida** [comment]
The predictions pagination on author's profile looks clunk and it doesn't work very well with the page as it is. I'm moving it to an issue and closing this PR without it

**Pull request merged**
